version: 2

jobs:
  ci-jqwik:
    working_directory: ~/work
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: cd jqwik && ./gradlew build
      - store_test_results:
          path: jqwik/build/test-results
  ci-junit5:
    working_directory: ~/work
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: cd junit5 && ./gradlew build
      - store_test_results:
          path: junit5/build/test-results
  ci-spring-data-jdbc:
    working_directory: ~/work
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: cd spring-data-jdbc && ./gradlew build
      - store_test_results:
          path: spring-data-jdbc/build/test-results
  ci-spring-data-redis:
    working_directory: ~/work
    machine: true
    steps:
      - checkout
      - run: cd spring-data-redis && ./gradlew build
      - store_test_results:
          path: spring-data-redis/build/test-results
  ci-strongly-typed-vs-javax-validation:
    working_directory: ~/work
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: cd strongly-typed-vs-javax-validation && ./gradlew build
      - store_test_results:
          path: strongly-typed-vs-javax-validation/build/test-results

workflows:
  version: 2
  ci-build:
    jobs:
    - ci-jqwik
    - ci-junit5
    - ci-spring-data-jdbc
    - ci-spring-data-redis
    - ci-strongly-typed-vs-javax-validation
